name: ReactAppPipeline

trigger: none

pool: 
  vmImage: ubuntu-latest

stages:
- stage: buildingApp
  jobs:
  - job: BuildReactApp
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '16.x'
    - task: Npm@1
      inputs:
        command: 'install'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/build'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    
- stage: deployingApp
  jobs:
  - job: ManualValidation
    pool: server
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'tomarrishav@gmail.com'
  - job: deployingReactApp
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(Build.ArtifactStagingDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'LearningsOwner'
        appType: 'webApp'
        WebAppName: 'ReactWebAppRishav'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/drop'
    
    