name: ReactPipeLine

trigger: 
 branches:
   include:
   - main

pool: Default

jobs:
  - job: BuildApp
    displayName: Building React App
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '16.x'